In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/ine-rmotr-curriculum/FreeCodeCamp-Pandas-Real-Life-Example/refs/heads/master/data/sales_data.csv')
df

,Date,Day,Month,Year,Customer_Age,Age_Group,Customer_Gender,Country,State,Product_Category,Sub_Category,Product,Order_Quantity,Unit_Cost,Unit_Price,Profit,Cost,Revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
2,2014-03-23,23,March,2014,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,23,45,120,1366,1035,2401
3,2016-03-23,23,March,2016,49,Adults (35-64),M,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,20,45,120,1188,900,2088
4,2014-05-15,15,May,2014,47,Adults (35-64),F,Australia,New South Wales,Accessories,Bike Racks,Hitch Rack - 4-Bike,4,45,120,238,180,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113031,2016-04-12,12,April,2016,41,Adults (35-64),M,United Kingdom,England,Clothing,Vests,"Classic Vest, S",3,24,64,112,72,184
113032,2014-04-02,2,April,2014,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113033,2016-04-02,2,April,2016,18,Youth (<25),M,Australia,Queensland,Clothing,Vests,"Classic Vest, M",22,24,64,655,528,1183
113034,2014-03-04,4,March,2014,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",24,24,64,684,576,1260
113035,2016-03-04,4,March,2016,37,Adults (35-64),F,France,Seine (Paris),Clothing,Vests,"Classic Vest, L",23,24,64,655,552,1207

In [3]:
df.shape

(113036, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              113036 non-null  object
 1   Day               113036 non-null  int64
 2   Month             113036 non-null  object
 3   Year              113036 non-null  int64
 4   Customer_Age      113036 non-null  int64
 5   Age_Group         113036 non-null  object
 6   Customer_Gender   113036 non-null  object
 7   Country           113036 non-null  object
 8   State             113036 non-null  object
 9   Product_Category  113036 non-null  object
 10  Sub_Category      113036 non-null  object
 11  Product           113036 non-null  object
 12  Order_Quantity    113036 non-null  int64
 13  Unit_Cost         113036 non-null  int64
 14  Unit_Price        113036 non-null  int64
 15  Profit            113036 non-null  int64
 16  Cost              113036 non-null  int64
 17  Revenue           113036 non-null  int64
dtypes: int64(9), object(9)
memory usage: 15.5+ MB

In [5]:
df.columns=df.columns.str.lower()

In [6]:
df['date']=pd.to_datetime(df['date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   date              113036 non-null  datetime64[ns]
 1   day               113036 non-null  int64
 2   month             113036 non-null  object
 3   year              113036 non-null  int64
 4   customer_age      113036 non-null  int64
 5   age_group         113036 non-null  object
 6   customer_gender   113036 non-null  object
 7   country           113036 non-null  object
 8   state             113036 non-null  object
 9   product_category  113036 non-null  object
 10  sub_category      113036 non-null  object
 11  product           113036 non-null  object
 12  order_quantity    113036 non-null  int64
 13  unit_cost         113036 non-null  int64
 14  unit_price        113036 non-null  int64
 15  profit            113036 non-null  int64
 16  cost              113036 non-null  int64
 17  revenue           113036 non-null  int64
dtypes: datetime64[ns](1), int64(9), object(8)
memory usage: 15.5+ MB

In [7]:
X=df.drop(['date','day','year','age_group','profit','cost','revenue'],axis=1)
y=df['profit']

In [8]:
X.head(2)

,month,customer_age,customer_gender,country,state,product_category,sub_category,product,order_quantity,unit_cost,unit_price
0,November,19,M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120
1,November,19,M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120

In [9]:
cat_cols=[i for i in X.columns if df[i].dtypes=='O']
num_cols=[i for i in X.columns if df[i].dtypes!='O']

cat_cols,num_cols

(['month',
  'customer_gender',
  'country',
  'state',
  'product_category',
  'sub_category',
  'product'],
 ['customer_age', 'order_quantity', 'unit_cost', 'unit_price'])

In [10]:
df.head(2)

,date,day,month,year,customer_age,age_group,customer_gender,country,state,product_category,sub_category,product,order_quantity,unit_cost,unit_price,profit,cost,revenue
0,2013-11-26,26,November,2013,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950
1,2015-11-26,26,November,2015,19,Youth (<25),M,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120,590,360,950

In [11]:
#encoding

# 0->male
# 1->female

X['customer_gender']=X['customer_gender'].map({'M':0,'F':1})

In [12]:
X.head(2)

,month,customer_age,customer_gender,country,state,product_category,sub_category,product,order_quantity,unit_cost,unit_price
0,November,19,0,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120
1,November,19,0,Canada,British Columbia,Accessories,Bike Racks,Hitch Rack - 4-Bike,8,45,120

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

scaler=StandardScaler()
ohe=OneHotEncoder(drop='first',handle_unknown='ignore')

preprocessor=ColumnTransformer(
    [
        ("StandardScaler",scaler,num_cols),
        ("OneHotEncoder",ohe,cat_cols)
    ]
)

##### train test split

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.28,random_state=42)

In [15]:
X_train_scaled=preprocessor.fit_transform(X_train)
X_test_scaled=preprocessor.transform(X_test)

c:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:242: UserWarning: Found unknown categories in columns [3] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

In [16]:
X_train_scaled

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 774476 stored elements and shape (81385, 219)>

In [17]:
X_train_scaled.shape,X_test_scaled.shape

((81385, 219), (31651, 219))

##### model training and selection

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor

In [19]:
models={
    "LinearRegression":LinearRegression(),
    
    "DecisionTreeRegressor":DecisionTreeRegressor(random_state=42),
    "GradientBoostingRegressor":GradientBoostingRegressor(random_state=42),
    "AdaBoostRegressor":AdaBoostRegressor(random_state=42)
}

In [20]:
models.items()

dict_items([('LinearRegression', LinearRegression()), ('DecisionTreeRegressor', DecisionTreeRegressor(random_state=42)), ('GradientBoostingRegressor', GradientBoostingRegressor(random_state=42)), ('AdaBoostRegressor', AdaBoostRegressor(random_state=42))])

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

In [22]:
for name,model in models.items():
    print(f"{name} training")
    print()

    model.fit(X_train_scaled,y_train)

    y_train_pred=model.predict(X_train_scaled)

    y_test_pred=model.predict(X_test_scaled)

    
    print("🔹 TRAINING PERFORMANCE")
    print("MAE:", mean_absolute_error(y_train, y_train_pred))
    print("MSE:", mean_squared_error(y_train, y_train_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
    print("R2 Score:", r2_score(y_train, y_train_pred))

    print()

    print("🔹 TESTING PERFORMANCE")
    print("MAE:", mean_absolute_error(y_test, y_test_pred))
    print("MSE:", mean_squared_error(y_test, y_test_pred))
    print("RMSE:", np.sqrt(mean_squared_error(y_test, y_test_pred)))
    print("R2 Score:", r2_score(y_test, y_test_pred))
    print("\n" + "="*40 + "\n")
    print()

LinearRegression training

🔹 TRAINING PERFORMANCE
MAE: 125.04938192301759
MSE: 61986.93615771969
RMSE: 248.97175775119493
R2 Score: 0.6989067177609259

🔹 TESTING PERFORMANCE
MAE: 126.8313528372115
MSE: 61519.16843722446
RMSE: 248.0305796413508
R2 Score: 0.7018897245214122

========================================


DecisionTreeRegressor training

🔹 TRAINING PERFORMANCE
MAE: 0.0
MSE: 0.0
RMSE: 0.0
R2 Score: 1.0

🔹 TESTING PERFORMANCE
MAE: 1.7324887049382327
MSE: 397.72850778806355
RMSE: 19.943131845025334
R2 Score: 0.998072682742073

========================================


GradientBoostingRegressor training

🔹 TRAINING PERFORMANCE
MAE: 39.74079021280846
MSE: 5760.495709219159
RMSE: 75.89792954500906
R2 Score: 0.9720191597145603

🔹 TESTING PERFORMANCE
MAE: 40.112293831139766
MSE: 5764.9025475873905
RMSE: 75.92695534253556
R2 Score: 0.9720643706632321

========================================


AdaBoostRegressor training

🔹 TRAINING PERFORMANCE
MAE: 109.30702059781301
MSE: 30723.47284380163
RMSE: 175.28112517838773
R2 Score: 0.8507648247562041

🔹 TESTING PERFORMANCE
MAE: 111.08345029250845
MSE: 31007.89913831022
RMSE: 176.09059923320785
R2 Score: 0.8497415750415014

========================================

##### hyperparameter tuning

In [25]:
gb=GradientBoostingRegressor()

In [26]:
gb

GradientBoostingRegressor()

In [24]:

GradientBoosting_params={
        "n_estimators": [50, 100,120,20],
        "learning_rate": [0.01, 0.1],
        "max_depth": [3, 5,4,2],
        "subsample": [0.8, 1.0]
}

In [29]:
from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(gb,param_grid=GradientBoosting_params,cv=5,n_jobs=-1,scoring='r2')

grid.fit(X_train_scaled, y_train)

print("Best Params:", grid.best_params_)
print("Best Score:", grid.best_score_)

Best Params: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 120, 'subsample': 1.0}
Best Score: 0.9854500721805

In [37]:
gb=GradientBoostingRegressor(learning_rate=0.1,max_depth=5,n_estimators=120,subsample=1.0)

gb.fit(X_train_scaled,y_train)

y_pred=gb.predict(X_test_scaled)

print("🔹 TESTING PERFORMANCE")
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))
print("\n" + "="*40 + "\n")
print()

🔹 TESTING PERFORMANCE
MAE: 16.456482227213986
MSE: 962.6353939412043
RMSE: 31.026366109185332
R2 Score: 0.9953352506257284

========================================

In [39]:
import pandas as pd

data = {
    "month": ["November", "May"],
    "customer_age": [19, 19],
    "customer_gender": [0, 1],
    "country": ["Canada", "Canada"],
    "state": ["British Columbia", "British Columbia"],
    "product_category": ["Accessories", "Accessories"],
    "sub_category": ["Bike Racks", "Bike Racks"],
    "product": ["Hitch Rack - 4-Bike", "Hitch Rack - 4-Bike"],
    "order_quantity": [8, 2],
    "unit_cost": [45, 20],
    "unit_price": [120, 100]
}

df = pd.DataFrame(data)

new_df_scaled=preprocessor.transform(df)

pred=gb.predict(new_df_scaled)

print("prediction:",pred[0])
print("prediction:",pred[1])

prediction: 571.5312375498753
prediction: 285.45862252753466